server:
  port: 8080

spring:
  datasource:
    username: root
    password: 12345678
    url: jdbc:mysql://localhost:3306/blog
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  type-aliases-package: com.hsp.entity
# JWT
jwt:
  header: Authorization
  secret: mySecret
  #token有效期一天
  expiration: 86400
  tokenHead: "Bearer "

#showSql
logging:
  level:
    cn:
      hsp:
        mapper : debug
